### ISSUE TITLE
How does "Number of columns" parameter works in quick edit form?

### ISSUE THREAD

**Issue by combluotion** [carfup/PCFControls#122]
What is used as separator?
Regards,
Diego.

**Comment by carfup** [comment]
Well the split by columns is pretty simple for now.
It counts the number of controls and split those based on the number.
X controls / X columns = number of controls displayed in each column by order in the form definition.

**Comment by combluotion** [comment]
Thank you for the information! 
I'll close the issue.
Regards,
Diego.
