### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aronmek** [carfup/PCFControls#124]
Hi, I'm very impressed with the PCF Quick Edit control.
Are there any options for a more commercial friendly license such as MIT?

Do you mind changing the license?

Best regards.

**Comment by carfup** [comment]
Hello,
Changing the licence is not really the plan.
What's yours to understand the ask ?

**Comment by aronmek** [comment]
I would like to use the component in a commercial product and I'm
uncomfortable including GPL components in the product.
Would you be open for licensing/support discussion?

**Comment by carfup** [comment]
As of today the licence will remain the same.
If that change I'll keep you posted.
Regards
