### ISSUE TITLE
PCF : Quick Edit Form not showing up in the controls field settings

### ISSUE THREAD

**Issue by nathanf5** [carfup/PCFControls#128]
Hi,

After installing your managed PCF : Quick Edit Form solution, and adding a lookup field onto a form - I cannot see the PCF : Quick Edit Form Control to add as a Control to the new look up field.

Any thoughts why this could be the case? and is anyone potentially experiencing this issue after enabling the Recent 2021 release.

Thanks,

![image](https://user-images.githubusercontent.com/60965414/128853133-ab74a2d4-736f-4ee4-a0db-146d4ef9ce7c.png)

**Comment by carfup** [comment]
Hello @nathanf5 ,

Thanks for your feedback.
When I first created the control, the lookup field binding was not supported for us.
However, I prepared a version to be used with a lookup field and this should be published beginning of september as i'm on holidays.
I keep you posted !

**Comment by carfup** [comment]
In the meantime, you can attach the control to a dummy text field!

**Comment by carfup** [comment]
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0
