### ISSUE TITLE
1044 Norwegian

### ISSUE THREAD

**Issue by thomassandsor** [carfup/PCFControls#13]
I tried adding 1044 Norwegian as a file in string library, but never actually used GitHub directly. Therefore I am not sure I have done it correctly:)

**Comment by DynamicsNinja** [comment]
Feel free to ping me if you still need help with it 😉

**Comment by carfup** [comment]
@DynamicsNinja Thanks for your support here !
Thomas sent me the file to be integrated.

I will integrate it probably tomorrow along with your translation.

**Comment by carfup** [comment]
The Norwegian language was included for the release of next week. 
Thanks for your help here !
