### ISSUE TITLE
Idea: read only field and required.... quick edit form

### ISSUE THREAD

**Issue by vernetmatias** [carfup/PCFControls#135]
Hello Clement, me again with a new request. Add the posibility to block a field (read only.).., the requirment is that I have a field that first is empty but the when the user complete the field and saves it i want to block it. And another thing is to make some fields required...

Thanks!!!

**Comment by carfup** [comment]
Hello Matias,
In fact you already can do it !
If in the quick view form you set a field as readonly, it will reflect in the control.
Regarding the required, it's based on the field level, if you see the field as required it will be the case in the control too.
Does it answers your need ?

**Comment by carfup** [comment]
not possible as far as I know and in a supported way.
the control lives in it's own world and we can integrate external js in it.
I do have a "fixed" way to call the fields "qef_fieldname" or something but you couldn't really force the required from there i guess and you would access the fields with dom elements which is not supported
