### ISSUE TITLE
Always loading - with latest 1.4.0.0

### ISSUE THREAD

**Issue by johnnylawson** [carfup/PCFControls#144]
Going through the issues here I haven't seen one like this:

The quickedit works but it never stops loading. It also removes the fields if I press refresh and same loading graphic.
![Screenshot 2021-09-22 113522](https://user-images.githubusercontent.com/2585357/134375353-66e97ad4-a186-4347-8669-d9a93b39b7ba.png)

It does look like this is flagging in the console:
![Screenshot 2021-09-22 113838](https://user-images.githubusercontent.com/2585357/134375561-7a309862-8c54-49f1-882e-f0e825040a8b.png)

My textfield with the control settings
![Screenshot 2021-09-22 113946](https://user-images.githubusercontent.com/2585357/134375958-dfe4a555-d11c-467a-bbd1-580e674cce33.png)

any top of the head ideas?

I do not have any js or business process flows attached to the lookup field.

**Comment by carfup** [comment]
Hello @johnnylawson ,

Sorry for the annoying behavior here, I'll try to reproduce this one my side and let you know.
Side try in the meantime, could you maybe try the "Lookup" version of the control, just to see if you have the same behavior ?

Thanks a lot

**Comment by carfup** [comment]
Any chance you could reach me on LinkedIn maybe to figure this out with a trial instance where you could reproduce it and I could have access ? 
I can't reproduce the behavior on several environments on my end ...

**Comment by johnnylawson** [comment]
This was resolved by creating a new QuickView form with identical fields in it and assigning that view to the Lookup version of the control. Thanks for your remote help!
