### ISSUE TITLE
Idea: call function on save success 

### ISSUE THREAD

**Issue by thomassandsor** [carfup/PCFControls#15]
Would it even be possible to call a Javascript function on successfull save?

My idea is that your form is smart for updating data in lookup entity. When the entity is updated, the current form might need a refresh or something like that. In this case we could call our own Javascript function. The function name could be inserted where we setup the pcf with lookup name etc.

Not even sure if possible:)

**Comment by carfup** [comment]
As you can guess, it's really complicated to implement something is this direction for now.
I'm keeping the issue open for now, maybe great news will come from MS side some day "soon".

**Comment by carfup** [comment]
Hey Thomas,
I'm cleaning a bit the issues here.
Since MS deployed the Form Component, I'm maintaining the current version but won't spend too much time on new things.
