### ISSUE TITLE
Any Composite - System Required Fields Not Enforced

### ISSUE THREAD

**Issue by lforte337** [carfup/PCFControls#160]
We are on version 1.4.0.0 of the Carfup_PCFControls.  It is a great tool, but we have run into an issue with using it. 

We have included system required fields in our Any Composite setup and they are not being enforced on save (see the steps below for details of our setup and testing).  

When we saw that the composite field wasn't enforcing the required fields we thought perhaps the composite field itself had to be set to required.  However, that did not resolve our issue either.  Because not all the fields are included in the composite are required, if just one of the optional fields is populated, the record will save and will not enforce the system requirement of the other fields in the composite. 

Steps to duplicate our issue: 
1. On Contact entity, set the OTB field **First Name to Required** 
2. On Contact entity, set the OTB field **Last Name to Optional** 
3. On Contact entity, create customer single line text field called Full Name 
4. Add the 3 above fields to a Contact Form 
5. Add the Any Composite Control to the customer Full Name field 
6. Configure Any Composite Control by adding Field 1 = First Name and Field 2 = Last Name
7. Save and Publish the above updates
8. Create a New Contact Record 
9. Click on the custom Full Name field 
10. Populate only the Last Name field in the composite control
11. Click Done to exit the composite control
12. Save the contact record 
      - Expected Result: Error message advises user that First Name field is required and prevent save 
      - Actual Result: Field requirement for First Name is not enforced, contact record is saved

**Comment by carfup** [comment]
Hi @lforte337 ,

Sorry for the late answer here ...
I was checking your use case, by default it was making sense since the required field was not on the form, the "blocking" notification was not triggered.

Here what I thought as a fix, blocking the "Done" button until all required fields are not filled : https://carfupstorage.blob.core.windows.net/sharex/2023_07_12_15-54-31_msedge.gif

Is that a fair way to handle your case ?

**Comment by carfup** [comment]
Please find the fix in the latest release  : https://github.com/carfup/PCFControls/releases/tag/1.4.0.1
Sorry for the delay :)
