### ISSUE TITLE
Idea - Allow opening the quick edit in a side panel

### ISSUE THREAD

**Issue by Sheeley7** [carfup/PCFControls#17]
This looks awesome! Would you consider adding support for a pop out version that uses the fabric UI panel? This way it would open like the current quick create form does.
[Office Fluent UI](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel)

In your comment on your page, I'm not sure what you mean by a PCF that will somehow become empty.

Do you feel this PCF will be superseded by the new Xrm.Navigation.nagivateTo functionality?

**Comment by carfup** [comment]
Hello Sheeley,
Thanks for your feedback here.
As said, the "navigateTo" functionality already allow you to easily open a modal form with the fields you want AND the JS logic behind.
This is basically the same thing having the form in a panel UI or in a modal according to me.
And if I would use the panel UI, on the form, there is nothing to be displayed anymore except a button : "Open my form" ?

**Comment by carfup** [comment]
I take the chance to close this issue as the Panel idea as discussed won't be implemented in that control.
Thanks for your suggestion !
