### ISSUE TITLE
An error occurred undefined - Editable QView Form

### ISSUE THREAD

**Issue by Karuna2Karan** [carfup/PCFControls#18]
I'm getting this error > An error occurred undefined.

Added the control on std fax field, trying to show the 'account contact card' via the primary contact lookup field in the Account form.

![image](https://user-images.githubusercontent.com/54361970/81850991-74abbd80-9561-11ea-964b-a0a933626873.png)

Configuration:
![image](https://user-images.githubusercontent.com/54361970/81850898-4ded8700-9561-11ea-88ae-3df60997fcc8.png)

I'm I doing something wrong??

**Comment by carfup** [comment]
Hello,
I tried on my environment with the same scenario and it worked fine.
Can you tried to load the control with another record and tell me if the error occur as well ?
If so, maybe you send me some details from the Developer tools (F12) regarding error messages or traces, to help me investigate ?
Thanks

**Comment by carfup** [comment]
Feel free to reopen the ticket if you have more insights so I can help you.

Clément
