### ISSUE TITLE
Could not find a property named 'undefined' on type 'Microsoft.Dynamics.CRM

### ISSUE THREAD

**Issue by dkassian** [carfup/PCFControls#2]
Hi,
Having an issue where the I am getting the message "Could not find a property named 'undefined' on type 'Microsoft.Dynamics.CRM._documententityname_" when I try to create a new record on a form with the File upload control present.

My setup:

- File control is on parent entity (crca7_equipmentrental(s))
- File data field is on related entity (crca7_equipmentdocuments)
- This only happens if I go directly from the main crca7_equipmentrentals grid and click new. If I create an equipment rental from a different sub grid it appears to work.
![File Control Setups](https://user-images.githubusercontent.com/60455804/73414817-3ac5ec80-42cd-11ea-90a5-b3129d45a21f.jpg)

Would you be available for any custom support? This control is incredibly useful for our specific use case and it'd be great if we could get it working.

Thanks,
Dylan

**Comment by carfup** [comment]
Hello Dylan,

I'm sorry for the late reply. And really appreciate your great feedback here.
I will try to reproduce your issue by using a create new from a subgrid and get back to you if i need more input.
Keep in touch !

**Comment by carfup** [comment]
This PCF is not really useful now so I'll close that issue.
