### ISSUE TITLE
Idea - Add subgrids

### ISSUE THREAD

**Issue by daranpok** [carfup/PCFControls#21]
Hi, thank you for this awesome control!

I really have no idea if it's possible, but I thought of adding subgrids to have the ability to create related records to an account for example.

In the use case I'm thinking about, I have an appointment regarding an account and I can see the related annual budgets (custom entity) of the account on the appointment form and I would be able to create a new annual budget record for 2020.

I tried to add it in the actual control, I can't see the subgrid and the loading control doesn't seem to stop.

Don't know if my suggestion is relevant, but thanks again for the control!

**Comment by carfup** [comment]
Hello,
Thanks for the idea here.
I assume it's related to the Quick Edit Form control.
I will investigate the possibilities here, the design of the grids need to be completely redone, it's a lot of work here :).

**Comment by carfup** [comment]
Hey @daranpok ,
I'm cleaning a bit the issues here.
Since MS deployed the Form Component, I'm maintaining the current version but won't spend too much time on new things.
