### ISSUE TITLE
Siret Validator deletes the value when saving the record

### ISSUE THREAD

**Issue by Herald1360** [carfup/PCFControls#28]
PCF: Carfup.SiretValidator (version 1.3.0.0)
Dynamics version (crm4): Version du serveur: 9.1.0000.18350 (Wave 1), Version du client: 1.4.830-2005.3
Test on 4 different environment (also 3 different users).

Hello Olivier,
After filling in the Siret field with a valid number, when I save the record the field is filled in the db.
If I open the record the field is empty in the form (but the field is filled in the db).
Of course if I save the record again then the field is cleared.
For an existing record with a valid Siret number, if I open it the field is empty in the form. If I save the record then the field is emptied.
I think it occurs since Wave 1 have been deployed.

Many thanks !

**Comment by carfup** [comment]
Hello Herald,
Thanks for the feedback here.

This is now fixed in a side branch.

The release will come out later this week, I keep you updated once it's deployed !
Clément

**Comment by carfup** [comment]
Fixed is now available according to the Pull Request:  #29 
You can download the solution here : https://github.com/carfup/PCFControls/releases/tag/1.3.1.0
