### ISSUE TITLE
Label Lenght on QView Form

### ISSUE THREAD

**Issue by HollowCT** [carfup/PCFControls#30]
Hi, first of all this is a great control and has been a joy to put into use.

Second I've noticed an issue on the QView Form control and that is that moderately long labels tend to be buried under the inputs or rather the inputs tend to take most of the space one assigns to them

Thanks for listening!

**Comment by carfup** [comment]
Hello,

Thanks for your support and reporting, I'll try to have a look to this !
Stay tuned.

**Comment by Venny0303** [comment]
I am also facing same issue with label and Can we have alignment of fields in configuration as well. Currently it is defaulted to horizontal only.Is it possible to to keep vertical alignment.

**Comment by carfup** [comment]
Hi @Venny0303 ,
Just to make sure i'm aligned with your thought.
On a quick view form, you can't specify if the field label is on top of the field or next to it.
Is that what you are looking for ?

**Comment by carfup** [comment]
You can find the latest version with this included : https://github.com/carfup/PCFControls/releases/tag/1.3.2.0
Thanks !
