### ISSUE TITLE
Required Fields

### ISSUE THREAD

**Issue by rbaryolo** [carfup/PCFControls#39]
Embrace required fields

**Comment by carfup** [comment]
Hello,
Can you give a bit more inputs ?
Are you referring to the Any Composite Fields control ?

**Comment by rbaryolo** [comment]
Sorry for the short description. What i mean is required fields do not show as required in the quick edit form, I used the control to show contacts and it allow to erase the required field Last Name and save the entity.

**Comment by rbaryolo** [comment]
Do you get my point now @carfup ?

**Comment by carfup** [comment]
Hi,
Yeah I got your point, here is a sample of the implementation : 
https://carfupstorage.blob.core.windows.net/sharex/2020_07_30_09-07-27.gif
Does it answer your requirement ?

**Comment by carfup** [comment]
You can find the latest version with this included : https://github.com/carfup/PCFControls/releases/tag/1.3.2.0
