### ISSUE TITLE
Idea - Have the OOB call function available for a composite Phonenumber + extension

### ISSUE THREAD

**Issue by johnbbily** [carfup/PCFControls#43]
Goal : Have a clickable composite field (phone number + extension with separator) with the OOB function (opening task +  the Android/iOS phone App or potentially the VoIP system in place)

The separator is important,  In order to dial the phone number first and then the extension because Android and iOS does not react the same.

Android accepts both "," (directly) or ";" (need manual validation)
iOS only accepts ","

**Comment by carfup** [comment]
#62 the feature is now merged in the release branch, incoming !

**Comment by carfup** [comment]
You will find the link to the latest version here : https://github.com/carfup/PCFControls/releases/tag/1.3.3.0

Clément
