### ISSUE TITLE
File Type Control corrupts XLSX file data

### ISSUE THREAD

**Issue by joenewstrom** [carfup/PCFControls#52]
Hi Clement, first of all- I am a big fan and am greatly appreciative of your open source contributions.

I want to give you a heads up that this control corrupts the Base64 encoding on the file type, but I have to admit I have no idea how. All I know is that I can upload and download XLSX just fine through your control, but if I try to download an XLSX file using the SDK that I uploaded with your control, it is corrupted. I can upload with the default file control just fine and access with the SDK with no issues. I'm guessing something funny is happening in the upload process that encodes the metadata differently than the SDK expects, but haven't dug in that deeply.

Thanks again,

Joe

**Comment by carfup** [comment]
Hello Joe,

Thanks for reporting this.
To be honest, with the release of the Microsoft Control, my focus is not really on that control but I'll try to have a look.
What is surprising is that from the SDK or  WebApi the base64 of the file is the same so something is intriguing and I've to check this out !

I try to keep you updated.

**Comment by carfup** [comment]
This PCF is not really useful now so I'll close that issue.
