### ISSUE TITLE
Composite Anything Possible To Bind To Multiple Lines of Text

### ISSUE THREAD

**Issue by WittigCRM** [carfup/PCFControls#55]
It would be great if the composite anything could be bound to either a multi lines of text or single line of text object on the form.

**Comment by carfup** [comment]
@WittigCRM , the capabilities was added and will published with the next release later this week or next week !

![image](https://user-images.githubusercontent.com/15732100/91359970-e4367780-e7f5-11ea-90c1-dd4077353c51.png)

**Comment by WittigCRM** [comment]
Thank you so much!  You just made my day!

**Comment by carfup** [comment]
You will find the link to the latest version here : https://github.com/carfup/PCFControls/releases/tag/1.3.3.0

Clément
