### ISSUE TITLE
Idea: Use control for Quick Create

### ISSUE THREAD

**Issue by BenediktBergmann** [carfup/PCFControls#57]
It would be nice to be able to use your control even for quick create purposes incase there is no record related.

**Comment by carfup** [comment]
@BenediktBergmann 
Here is the result. Feel free to give your feedback, any changes is possible before merging into Master branch ! :) 

![quickcreateqef](https://user-images.githubusercontent.com/15732100/91294601-1619f080-e79a-11ea-85aa-61568976c592.gif)

**Comment by BenediktBergmann** [comment]
I think it is a Good implementation.
It is using the standard elements which is very good.
Thank you!

**Comment by carfup** [comment]
You will find the link to the latest version here : https://github.com/carfup/PCFControls/releases/tag/1.3.3.0

Clément
