### ISSUE TITLE
Idea: Add capability in Quick Edit Form to render as read only

### ISSUE THREAD

**Issue by ankitchawla23** [carfup/PCFControls#66]
Quick Edit Form is great and it provides two key benefits over an OOB Quick View Form, they are:

- Multi Column Layout
- Multi line fields

It would be great for this control to render as read only also. It can be used as an enhanced Quick View form also.

**Comment by carfup** [comment]
Hey Ankit,
Just as reminder, what if you just set the field 'holder" to read only , this will render the QEF as read only, can it be a solution for you ?

**Comment by ryannipper** [comment]
Hey @carfup I tried to set the holding field to read only and it didn't make the QEF read-only for me.  Is there any way around this?

Also, this form is great, so much better than the OOTB QV form

**Comment by carfup** [comment]
> Hey @carfup I tried to set the holding field to read only and it didn't make the QEF read-only for me. Is there any way around this?
> 
> Also, this form is great, so much better than the OOTB QV form

Hello @ryannipper ,
Indeed my bad, i must have failed the last release somehow ... it's now fixed and will be included in the next release .

**Comment by carfup** [comment]
Fix included in the latest version : https://github.com/carfup/PCFControls/releases/tag/1.33.1
Clément
