### ISSUE TITLE
Idea: Show data from a Grand Parent entity record

### ISSUE THREAD

**Issue by ankitchawla23** [carfup/PCFControls#67]
It would be great if we can display the data on the Quick Edit Form from a grandparent entity and not only Parent. 

We have a scenario where a grandparent entity, parent entity and transactional child entity are present. On the child entity, we would like to show the grandparent data in the PCF control.

**Comment by carfup** [comment]
Hey @ankitchawla23 ,
I'm cleaning a bit the issues here.
Since MS deployed the Form Component, I'm maintaining the current version but won't spend too much time on new things.
