### ISSUE TITLE
Date of Birth field showing "1/01/1970"

### ISSUE THREAD

**Issue by nrameshgoud** [carfup/PCFControls#68]
Thanks for this control this really saved our development time. I am facing one issue with the date field, will be thankful if someone help me to resolve this issue.
Date of birth field is optional in my contact form and this control is displaying "1/01/1970" it should be null as per the record data.
How can I set this value to null. This is misleading the users unable to differentiate its between actual value and this default value.
![DOB issue](https://user-images.githubusercontent.com/73111362/96444860-bf410c80-125a-11eb-85de-52aadaede579.JPG)

**Comment by carfup** [comment]
Thanks for raising this issue, I will check if I can reproduce this and fix it.
I keep you updated.

**Comment by carfup** [comment]
Just to keep you updated, a fix was push, this will be included in the next release !

**Comment by nrameshgoud** [comment]
> Just to keep you updated, a fix was push, this will be included in the next release !

Thank you so much for the fix. Waiting for the release may I know the expected next release date. This will really help us to plan the rollout this control.

**Comment by carfup** [comment]
I will do my best to push the release this week.

Clément

**Comment by carfup** [comment]
Fix included in the latest version : https://github.com/carfup/PCFControls/releases/tag/1.33.1
Clément

**Comment by nrameshgoud** [comment]
Thank you for the great control.
I have installed the updated release solution. Facing issue in UI after this release.
Attaching the issue screenshot. Please reply how to fix this labels and controls are not getting visible completely. it seems like css issue.
![UI Issue](https://user-images.githubusercontent.com/73111362/98532525-ecbb2c00-22d5-11eb-8c2d-69e83ef36fd3.JPG)

**Comment by carfup** [comment]
Hello,
Sorry to hear that you are facing this issue.
On my end with the latest version, all my screens are loading fine.
Can you try to attach the PCF to a new form just to make sure you have the same rendering?
What is the width of your section ?

**Comment by nrameshgoud** [comment]
Thank you are right other webresource css effected this. I removed it now.
The two optionset is still behaving different any inputs? please
![UI Issue2](https://user-images.githubusercontent.com/73111362/98622818-7c0c2200-235e-11eb-90db-21691e1d1e24.JPG)

**Comment by carfup** [comment]
Looks like the rendering was updated for some reason...
Can you try to download "again" the v1.3.3.1 https://github.com/carfup/PCFControls/releases/tag/1.3.3.1 and let me know ?

**Comment by nrameshgoud** [comment]
Yeah this is working now Thanks for the fix
