### ISSUE TITLE
 Displaying date with a day difference after refresh

### ISSUE THREAD

**Issue by venkata009** [carfup/PCFControls#69]
Nice Work!!!! I have a small question relating to date field. Its displaying date with a day difference. Do you know whats causing this issue and Do you have a workaround for this issue??
Your control was really helpful..

**Comment by carfup** [comment]
Hello,
Thanks for your feedback.
I'm not able to reproduce the issue unfortunately.
Few questions to try to understand the scenario : 
* what timezone are you using ?
* is it occuring only on Date field or on DateTime field as well ?
* Are you able to check the value of the date stored in the CDS using the API ? just to make sure I see the real difference.
As example i'm on GMT+1 so if I set 2020-10-27 00:00:00, on the API I will get 2020-10-26 23:00:00
But this should be handled by the control for the rendering so ...

**Comment by carfup** [comment]
Fix included in the latest version : https://github.com/carfup/PCFControls/releases/tag/1.33.1
Clément
