### ISSUE TITLE
Field names are not displaying display name from the form

### ISSUE THREAD

**Issue by nrameshgoud** [carfup/PCFControls#77]
Hi
This is great control which is helping my team.

Will be more happy if we get this fixed as well.

Field names are not displaying "Display" name from the form, it is getting name from the Entity field name
We have different display names in different forms, this is confusing users from actual form a and quick edit form
Attached the image which explains more.
It will be great with this change.
![name issue](https://user-images.githubusercontent.com/73111362/100029701-f0a68c80-2e45-11eb-91cd-5c1d7d770d9b.JPG)

**Comment by nrameshgoud** [comment]
Just checking if this is a valid issue or am I missing something.

**Comment by carfup** [comment]
Hello,
Thanks for reporting this, it was indeed in my todo list but I then forgot to make sure this was integrated within the last release.
I will take care of this in the next one !

**Comment by nrameshgoud** [comment]
Thank you for taking this up.
We are waiting for this change. When can we expect the next release? So
that we can plan our changes accordingly.
Really this control is doing awesome things.

**Comment by carfup** [comment]
Let's say as soon as I can spare time on my personal time, I will update it.

**Comment by carfup** [comment]
Fix is included in the latest release : https://github.com/carfup/PCFControls/releases/tag/1.3.3.2
Enjoy !
