### ISSUE TITLE
Managed Solution PCF names

### ISSUE THREAD

**Issue by thomassandsor** [carfup/PCFControls#8]
When importing, it doesn't show any names in the Custom Controls section of the solution (managed). Would look a little better if they had names:)

**Comment by carfup** [comment]
Will have a look to that, I planned a new release today or tomorrow so I keep you updated!

Thanks for the feedback.

**Comment by thomassandsor** [comment]
The unmanaged worked fine.. Since the solution is only PCF components, I don't really need the managed solution:)

**Comment by carfup** [comment]
Looks like the managed components have a special treatment in the "old" admin center.
On make.powerapps.com, it's fine.
