### ISSUE TITLE
Issue || "Open Quick Create Form" option instead of rendering the quick view.

### ISSUE THREAD

**Issue by asadTariq** [carfup/PCFControls#80]
Hello, 
I am new to Dynamics and PCF controls, i tried to integrate the control and passed the parameters as suggested by you, but i am facing an issue. Instead of loading the form, it gives an option to create a new opportunity. 
![image](https://user-images.githubusercontent.com/16046935/102077856-3e416400-3e0a-11eb-9f2b-4a6179638607.png)

I have created a new quick view in the Opportunity entity and passing its GUID in the guid paramter. i could not find a way to get the Guid from anyother source, i got it from the URL of the form. 
![image](https://user-images.githubusercontent.com/16046935/102078008-7c3e8800-3e0a-11eb-933e-7edefce75582.png)

this is the form i have created for this purpose. 
![image](https://user-images.githubusercontent.com/16046935/102078069-9aa48380-3e0a-11eb-9975-84fb6ba2f061.png)

and here is the configuration of the control,|
![image](https://user-images.githubusercontent.com/16046935/102078154-be67c980-3e0a-11eb-96c3-54820e8fdf64.png)

Could you please have a look and let me know what possible mistake i am making here?

Thanks in advance.

**Comment by carfup** [comment]
Hello,

Just to make sure we are on the same page.
Are you trying to display an opportunity record with the PCF from another entity or the other way around ?

The LookupFieldMapped needs to be the one related to the lookup field record you want to display on the form.
For non standard fields, you need to decorate it with "_FIELDNAME_value".

Let me know if this help.

**Comment by asadTariq** [comment]
Yes,
i am trying to display **opportunity** record in **Order** Entity. 

The form belongs to **Order** entity and has a lookup field from **opportunity**. The regular quick view is working fine(i am able to load data from Opportunity to the view in Order), I believe the problem is with my configuration of Control. 
Is the way of getting GUID correct?

**Comment by carfup** [comment]
Getting the form GUID from the URL is fine but your is not right
The %3D = { so your GUID starts from 352BA... and end with D85

Can you please try to use : "_opportunityid_value" in the LookupMappedField please ?

**Comment by asadTariq** [comment]
> Can you please try to use : "_opportunityid_value" in the LookupMappedField please ?

This works. Thanks a lot man  :')
