### ISSUE TITLE
custom behaviour and translation

### ISSUE THREAD

**Issue by krewie** [carfup/PCFControls#81]
Hi, i have a few that i was hoping could get answered. If this is not the appropriate place to put them then please notify me so that i can move them.

* Is it possible to add custom behaviour to the PCFControls i.e. to extend or edit current behaviour that better suits our needs ?

* We noticed that the translation in some languages are a little "off" for the refresh / update button, is there any way to customize those buttons or translations ?

**Comment by carfup** [comment]
Hello,
This is the right place to ask :)

- Adding custom behavior within the PCF control to make your own management of a field type is not possible as of today.
- For any translation issue, feel free to get back to me or making a pull request to integrate it. For some languages I used an automatic translator so I can understand it's not 100% accurate. Unfortunately, I don't speak all supported languages :p

**Comment by carfup** [comment]
Do you have feedbacks regarding the translations ? I'm preparing a release for tomorrow, otherwise, it will have to wait the next one.
