### ISSUE TITLE
Multiline text fields

### ISSUE THREAD

**Issue by sss999-cmd** [carfup/PCFControls#82]
Hi Clement,

This PCF (quick edit form) is really great and really helps improve user experience, so thanks very much.

Just a question around the multiline text fields: when entering the data, the text area automatically expands, so if I input 15 lines of text, the box shows all 15 lines at once.  However, when I refresh the main record or navigate away and come back, it goes back to 3.5 x line height and there is no scroll bar on the text area either, so it's hard to view more than the 3 lines of text at once.  Is it possible to have the text areas of these multiline text fields always expand to match the length of the content?  So if I'm coming back to view my 15 lines of text I can see all 15 lines of text at once?

**Comment by carfup** [comment]
Hello,
Thanks for reporting this.
I will check the capabilities I have around the control.
I'm shared between auto-expanding it which could take a lot of spaces on the form based on the content and add a scrollbar if possilbe.
I keep you updated.

**Comment by carfup** [comment]
Fix is included in the latest release : https://github.com/carfup/PCFControls/releases/tag/1.3.3.2
Enjoy !

**Comment by sss999-cmd** [comment]
Awesome, thanks so much, I'll check it out :)
