### ISSUE TITLE
not showing custom field labels

### ISSUE THREAD

**Issue by leibishr** [carfup/PCFControls#83]
Hi,

we discovered this PCF Control on pcf gallery and i must say it is truly amazing. cuts out so much custom development that is required to accomplish what you did. so thanks.

but i did notice 2 small issues from my end, if i change the label of one of the fields on the quick view form, the custom control uses the default label of the given field.
the second issue i noticed; we have a requirement where we want to use this control twice on the same form but load different quick view forms for each instance. i followed the documentation and entered different form ids for the separate instances but the same form shows by both areas.

Once again, thanks.
Leibish Ringel

**Comment by carfup** [comment]
Hello,
Thanks for your feedback.
The label fix is in progress.
Are you trying to map different form from the same lookup ? or different lookup on the same form ?
Can you show me the configurations and rendering to figure this out ?

**Comment by leibishr** [comment]
hey,
thanks for your response.
do you know roughly when the fix for the label will be released?
regarding the quick view forms, we are using 2 different quick view forms and 2 different lookups as well (using different data from the same entity).
i just checked the configuration and rendering on the form to get screenshots and it seems to be working properly now (I didn't change anything now).
when we initially configured it it wasn't working properly, I'm not sure what changed. i guess ill reach out if it happens again.
Thanks for your help.
Leibish Ringel

**Comment by carfup** [comment]
Fix is included in the latest release : https://github.com/carfup/PCFControls/releases/tag/1.3.3.2
Enjoy !
