### ISSUE TITLE
Carfup - French SIRET Validator PCF

### ISSUE THREAD

**Issue by Herald1360** [carfup/PCFControls#87]
If we make the field read-only and then unlock it, we can no longer type in the field (the screen must be refreshed to be able to access the field again)
Carfup version 1.3.3.2

**Comment by carfup** [comment]
Hello Herald,

Thanks for reporting this, I will have a look into this and if I can reproduce this I'll provide a fix included in the next release !

**Comment by carfup** [comment]
The fix was developed and will be included within the next release !

**Comment by carfup** [comment]
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0
