### ISSUE TITLE
Idea - Multiple Lines in Any Composite Field

### ISSUE THREAD

**Issue by VastConfinement** [carfup/PCFControls#88]
The composite field control is great in that it brings back a much needed feature to manage space. One of the biggest culprits requiring this are addresses. Presently the composite control allows you to enter a separator such as a comma or space.

It would be nice if it would be possible to add newline as a character to format the address in multiple lines. 

One up from that would be to specify a specific format using fields in the composite and separators such as:
address1_street1CRLFaddress1_street2CRLFaddress1_city,%20address1_stateorprovince%20address1_postalcode

which would return:
address1_street1
address1_street2
address1_city, address1_stateorprovince address1_postalcode

**Comment by carfup** [comment]
Hello @VastConfinement ,
That's definitely something i'm going to check for the next release !
Thanks for the feedback.

**Comment by carfup** [comment]
The fix was developed and will be included within the next release !

**Comment by carfup** [comment]
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0
Wiki will be updated later today to explain how to use it.
