### ISSUE TITLE
IBAN Validator - Field value not refreshing with setValue

### ISSUE THREAD

**Issue by FlorentF** [carfup/PCFControls#89]
The field doesn't seem to refresh on the form when updating the value with xrm's .setValue function.
Value is well filled, it can be retrieved with .getValue function afterward but the value edit doesn't show. Only after reloading the form does it show the updated value.

**Comment by carfup** [comment]
Thanks for the feedback.
The fix was developed and will be included within the next release !

**Comment by carfup** [comment]
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0
