### ISSUE TITLE
Customer Lookup

### ISSUE THREAD

**Issue by thomassandsor** [carfup/PCFControls#9]
Will it be possible to support the Customer Lookup on Contact? parentcustomerid I believe it is called:)

**Comment by carfup** [comment]
Good point, I will check the possibility to manage polymorphic lookups !

**Comment by thomassandsor** [comment]
If not capable of managing Polymorphic it would work fine for me to hardcore lock the lookups in PCF configuration IF that were even possible. I see though that Polymorphic can be a bit of a challenge:) Excited to hear more about it.. 

Already loving the solution big time!

**Comment by carfup** [comment]
#14 The feature is almost ready, stay tuned for next week update !

**Comment by carfup** [comment]
Here is the release which handle the customer field : https://github.com/carfup/PCFControls/releases/tag/1.2.1.0

Enjoy !
