### ISSUE TITLE
unspecific error message in case of missing permissions

### ISSUE THREAD

**Issue by soniawo** [carfup/PCFControls#90]
Hello,
I noticed that users receive an unspecific error message ('An error occurred: [object Object]') when trying to use the Quick Edit Form to view data from an entity they do not have access to. Is it possible to hide it or give them more meaningful information within it?
![image](https://user-images.githubusercontent.com/80264275/110328723-fbafb200-801b-11eb-81f7-72c58c875af3.png)

**Comment by carfup** [comment]
Thanks for the feedback, I'm fixing it !

**Comment by carfup** [comment]
Message will be replaced by : 
"You do not have enough privileges to access the Microsoft Dynamics 365 object or perform the requested operation. For more information, contact your Microsoft Dynamics 365 administrator."

Clément

**Comment by carfup** [comment]
The release 1.4.0.0 is available to fix this : https://github.com/carfup/PCFControls/releases/tag/1.4.0.0
